apiVersion: v1
kind: Secret
metadata:
  name: workercontagemsecret
type: Opaque
data:
  ConnectionSqlServer: <CONNECTION STRING DO SQL SERVER/AZURE SQL EM BASE 64>
  ConnectionApacheKafka: <CONNECTION STRING DO AZURE EVENT HUBS EM BASE 64>
  UsernameApacheKafka: $ConnectionString
  SaslApacheKafka: plaintext
  TlsApacheKafka: enable
  ConnectionAppInsights: <CONNECTION STRING DO APPLICATION INSIGHTS EM BASE 64>